pipeline {
    agent {
        docker { image 'node:20' }
    }

    stages {
        stage('Setup') {
            steps {
                checkout scmGit(
                    branches: [[name: env.BRANCH_NAME]],
                    browser: github('https://github.com/patthomasrick/hugo-patrickwthomas.net-2'),
                    extensions: [submodule(recursiveSubmodules: true, reference: '')],
                    userRemoteConfigs: [
                        [
                            credentialsId: 'github-hugo-patrickwthomas.net-2',
                            url: 'git@github.com:patthomasrick/hugo-patrickwthomas.net-2.git'
                        ]
                    ]
                )

                sh '''
                wget -q https://github.com/gohugoio/hugo/releases/download/v0.112.3/hugo_extended_0.112.3_linux-amd64.deb -O /tmp/hugo.deb
                dpkg -i /tmp/hugo.deb

                apt update
                apt install -y zip

                npm install -g pnpm wrangler

                pnpm install
                cd themes/bauxite
                pnpm install
                cd ../..
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                cd themes/bauxite
                pnpm run build
                cd ../..

                pnpm run build:local

                zip -r public.zip public
                '''
            }

            post {
                success {
                    archiveArtifacts 'public.zip'
                }
            }
        }

        stage('Deploy') {
            // Only deploy if the branch is main or develop
            when {
                anyOf {
                    branch 'main'
                    branch 'develop'
                }
            }
            steps {
                withCredentials([string(credentialsId: 'cloudflare-workers-patrickwthomas.net', variable: 'CLOUDFLARE_API_TOKEN')]) {
                    sh '''
                    wrangler pages deploy ./public --project-name hugo-patrickwthomasnet-2
                    '''
                }
            }
        }
    }
}
