pipeline {
    agent {
        docker { image 'node:20' }
    }

    stages {
        stage('Setup') {
            steps {
                checkout scmGit(branches: [[name: env.BRANCH]], browser: github('https://github.com/patthomasrick/hugo-patrickwthomas.net-2'), extensions: [submodule(recursiveSubmodules: true, reference: '')], userRemoteConfigs: [[credentialsId: 'github-hugo-patrickwthomas.net-2', url: 'git@github.com:patthomasrick/hugo-patrickwthomas.net-2.git']])

                sh '''
                wget -q https://github.com/gohugoio/hugo/releases/download/v0.112.3/hugo_extended_0.112.3_linux-amd64.deb -O /tmp/hugo.deb
                dpkg -i /tmp/hugo.deb

                apt update
                apt install -y zip

                npm install -g pnpm

                cd themes/bauxite
                pnpm install
                cd ../..
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                cd themes/bauxite
                pnpm run build
                cd ../..
                '''

                sh '''
                cd themes/bauxite
                npm install
                npm run build
                cd ../..
                '''

                sh '''
                hugo --gc --minify
                zip -r public.zip public
                '''
            }

            post {
                success {
                    archiveArtifacts 'public.zip'
                }
            }
        }
    }
}
